package com.nimo.backend;

import com.sun.net.httpserver.*;import java.io.*;import java.net.*;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import java.util.concurrent.*;import java.util.regex.*;

public class NimoServer {
 static final Map<String,String> users=new ConcurrentHashMap<>(); static final HttpClient client=HttpClient.newHttpClient();
 public static void main(String[] a)throws Exception{HttpServer s=HttpServer.create(new InetSocketAddress(8080),0);s.createContext("/api/auth",NimoServer::auth);s.createContext("/api/chat",NimoServer::chat);s.createContext("/health",e->send(e,200,"{\"ok\":true,\"service\":\"Nimo\"}"));s.setExecutor(Executors.newCachedThreadPool());s.start();System.out.println("Nimo server listening on http://localhost:8080");}
 static void auth(HttpExchange e)throws IOException{if(!e.getRequestMethod().equals("POST")){send(e,405,"{}");return;}String raw=read(e),email=value(raw,"email").toLowerCase(),pw=value(raw,"password");if(email.length()<5||pw.length()<4){send(e,400,"{\"error\":\"Invalid credentials\"}");return;}try{users.putIfAbsent(email,hash(pw));send(e,200,"{\"ok\":true,\"email\":\""+esc(email)+"\"}");}catch(Exception x){send(e,500,"{\"error\":\"Server error\"}");}}
 static void chat(HttpExchange e)throws IOException{if(!e.getRequestMethod().equals("POST")){send(e,405,"{}");return;}String q=value(read(e),"message"),local=local(q);if(local==null)local=live(q);send(e,200,"{\"reply\":\""+esc(local)+"\"}");}
 static String local(String q){String x=q.toLowerCase();if(x.contains("who are you"))return"I’m Nimo, your calm and capable voice assistant.";if(x.contains("time"))return"It’s "+new java.text.SimpleDateFormat("h:mm a",Locale.US).format(new Date())+".";if(x.contains("help"))return"I can answer questions, open websites, set quick timers, and speak replies aloud.";return null;}
 static String live(String q){String key=System.getenv("OPENAI_API_KEY");if(key==null||key.isBlank())return"I’m in offline mode. Add OPENAI_API_KEY to the Java server to enable live AI answers.";try{String model=System.getenv().getOrDefault("OPENAI_MODEL","gpt-4o-mini"),body="{\"model\":\""+esc(model)+"\",\"messages\":[{\"role\":\"system\",\"content\":\"You are Nimo, a warm, concise assistant. Never claim to control systems you cannot access.\"},{\"role\":\"user\",\"content\":\""+esc(q)+"\"}]}";HttpRequest r=HttpRequest.newBuilder(URI.create(System.getenv().getOrDefault("OPENAI_BASE_URL","https://api.openai.com/v1")+"/chat/completions")).header("Authorization","Bearer "+key).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body)).build();String out=client.send(r,HttpResponse.BodyHandlers.ofString()).body();Matcher m=Pattern.compile("\\\"content\\\"\\s*:\\s*\\\"((?:\\\\.|[^\\\"])*)\\\"").matcher(out);return m.find()?m.group(1).replace("\\n","\n"):"The AI service returned no text.";}catch(Exception x){return"I couldn’t reach the live AI service. Check the server configuration.";}}
 static String value(String json,String key){Matcher m=Pattern.compile("\\\""+Pattern.quote(key)+"\\\"\\s*:\\s*\\\"((?:\\\\.|[^\\\"])*)\\\"").matcher(json);return m.find()?m.group(1).replace("\\\"","\"").replace("\\\\","\\"):"";}static String read(HttpExchange e)throws IOException{return new String(e.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);}static String hash(String p)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");byte[] b=p.getBytes(StandardCharsets.UTF_8);for(int i=0;i<120000;i++)d.update(b);return Base64.getEncoder().encodeToString(d.digest());}static String esc(String x){return x.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n");}static void send(HttpExchange e,int code,String body)throws IOException{e.getResponseHeaders().add("Content-Type","application/json");e.getResponseHeaders().add("Access-Control-Allow-Origin","*");byte[] b=body.getBytes(StandardCharsets.UTF_8);e.sendResponseHeaders(code,b.length);try(OutputStream o=e.getResponseBody()){o.write(b);}}
}
